.TH CLIENT 1 "September 2025" "v0.4.1" "User Commands"
.SH NAME
client \- sample client program using myutils library
.SH SYNOPSIS
.B client
[\fIOPTIONS\fR]
.SH DESCRIPTION
The
.B client
program demonstrates usage of the myutils library.  
It provides basic functionality such as reading, writing, or processing input as per assignment tasks.

.SH AUTHOR
Toqeer Zafar <toqeerzafarm@gmail.com>

